### ISSUE TITLE
Can't change the date archived format

### ISSUE THREAD

**Issue by mathisgauthey** [omnivore-app/obsidian-omnivore#80]
I like to have a timeline of things.
Hence I organised my YAML with these dates :

```YAML
state: ARCHIVED
date_published: 2020-01-12 14:30:44
date_saved: 2023-06-07 08:29:42
date_read: 2023-06-07 08:53:33
date_archived: 2023-06-07T07:53:28.396Z
```

The issue is that there is no way to change the archived date format as of today.

Thanks in advance !
